install.packages("plotrix")
library(plotrix)
x <- c(44,34,23,60)
label <-c("Karachi","Lahore","Multan","Okara")
head(label)
head(x)
pie(x,label)
pct <- round(x/sum(x)*100)
lbls <- paste(label,pct)
lbls <- paste(lbls,"%",sep="")
pie(x,labels = lbls,col=rainbow(length(lbls)),main = "City Wise Smoke Pie Chart")
legend("topright",c("Karachi","Lahore","Multan","Okara"),label,cex = 0.5,fill = rainbow(length(x)))
pie3D(x,labels = lbls,explode = 0.1,main="City_Pie_Chart")
